services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://flattracker:${DB_PASSWORD}@db:5432/flattracker
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
      init-db:
        condition: service_completed_successfully
      
  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=flattracker
      - POSTGRES_USER=flattracker
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    expose:
      - 5432
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data: