import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import Link from "next/link"
import "./globals.css"

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
})

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <header className="px-6 py-2 w-full bg-indigo-600 text-white flex items-center justify-between">
                    <Link href="/" className="font-bold text-xl">
                        Shared Flat Tracker
                    </Link>
                    <nav className="flex space-x-4">
                        <Link href="/trackers">Trackers</Link>
                        <Link href="/users">Users</Link>
                    </nav>
                </header>
                <main>{children}</main>
            </body>
        </html>
    )
}
