name: Build on Tag
run-name: Build Docker Images on Tag

on:
  push:
    tags:
      - 'v*.*.*'  # Matches semantic versioning tags like v1.0.0, v2.1.3, etc.

permissions:
  contents: read  # Allows the workflow to read the repository contents
  packages: write  # Allows the workflow to push Docker images to GitHub Packages


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}  # Use the GITHUB_TOKEN for authentication

      - id: lower-repo
        shell: pwsh
        run: |
          "::set-output name=repository_owner::$($env:GITHUB_REPOSITORY_OWNER.ToLowerInvariant())"

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ghcr.io/${{ steps.lower-repo.outputs.repository_owner }}/shared-flat-tracker:${{ github.ref_name }}
            ghcr.io/${{ steps.lower-repo.outputs.repository_owner }}/shared-flat-tracker:latest
          cache-from: type=registry,ref=ghcr.io/${{ steps.lower-repo.outputs.repository_owner }}/shared-flat-tracker:latest
          cache-to: type=inline
